### ISSUE TITLE
Add Raspberry Pi GPIO Support

### ISSUE THREAD

**Issue by kiam001** [pix/heystack-nrf5x#2]
Hello,

I have bought the STflasher twice, unfortunately one accidental short circuit is enough and the part is a brick.

that's why i'm currently using my raspberry pi3 which works great.

Even in the event of an accidental short circuit, the raspberry pi restarts briefly but hasn't broken yet.

Works out of the box with apt install openocd and source [find interface/raspberrypi2-native.cfg] instead of [find interface/stlink.cfg]

**Comment by pix** [comment]
I updated the README.md to mention that. Thanks.
